homepage:
  path: /
  controller: App\Controller\CallBackController::index

registred:
  path: /registred
  controller: App\Controller\CallBackController::register

list:
  path: /list
  controller: App\Controller\CallBackController::listing

