homepage:
  path:
    fr: /
    en: /{_locale}
  controller: App\Controller\CallBackController::index
  requirements:
    _locale: fr_FR|en_EN


register:
  path:
    fr: /register
    en: /{_locale}/register
  controller: App\Controller\CallBackController::register
  requirements:
    _locale: fr_FR|en_EN

list:
  path:
    fr: /list
    en: /{_locale}/list
  controller: App\Controller\CallBackController::listing
  requirements:
    _locale: fr_FR|en_EN

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

verif:
  path:
    fr: /verif
    en: /{_locale}/verif
  controller: App\Controller\CallBackController::verify
  requirements:
    _locale: fr_FR|en_EN


