homepage:
  path: /
  controller: App\Controller\CallBackController::index

register:
  path: /register
  controller: App\Controller\CallBackController::register

list:
  path: /list
  controller: App\Controller\CallBackController::listing

