homepage:
  path: /{_locale}
  controller: App\Controller\CallBackController::index
  locale: fr

register:
  path: /{_locale}/register
  controller: App\Controller\CallBackController::register
  locale: fr

list:
  path: /{_locale}/list
  controller: App\Controller\CallBackController::listing
  locale: fr

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

verif:
  path: /{_locale}/verif
  controller: App\Controller\CallBackController::verify
  locale: fr


