homepage:
  path: /{_locale}
  controller: App\Controller\CallBackController::index
  locale: "%locale%"
  requirements:
    _locale: fr_FR|en_EN


register:
  path: /{_locale}/register
  controller: App\Controller\CallBackController::register
  locale: "%locale%"
  requirements:
    _locale: fr_FR|en_EN

list:
  path: /{_locale}/list
  controller: App\Controller\CallBackController::listing
  locale: "%locale%"
  requirements:
    _locale: fr_FR|en_EN

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

verif:
  path: /{_locale}/verif
  controller: App\Controller\CallBackController::verify
  locale: "%locale%"
  requirements:
    _locale: fr_FR|en_EN


